server:
  port: 12100

spring:
  application:
    name: jeeoklog-server
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:10000/
  zipkin:
    base-url: http://127.0.0.1:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  messages:
    basename: messages, errors

  datasource:
    url: jdbc:mariadb://localhost:3307/jeeoklog_post_db?allowPublicKeyRetrieval=true&useSSL=false
    username: jeeok_user
    password: jeeok_pass
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        ues_sql_comment: true
        default_batch_fetch_size: 1000
    open-in-view: true

#actuator config
management:
  endpoints:
    web:
      exposure:
        include: refresh

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
