server:
  port: 12500

spring:
  application:
    name: jeeokshop-notification-server
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:10000/

  datasource:
    url: jdbc:mariadb://localhost:3307/jeeokshop_notification_db?allowPublicKeyRetrieval=true&useSSL=false
    username: jeeok_user
    password: jeeok_pass
    driver-class-name: org.mariadb.jdbc.Driver