server:
  port: 12200

spring:
  application:
    name: jeeokshop-store-server
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:10000/
  zipkin:
    base-url: http://localhost:9411 #Open Zipkin 통신에 사용되는 URL
    enabled: true
  sleuth:
    sampler:
      probability: 1.0 #Open Zipkin 으로 데이터를 전송하는 트랜잭션 샘플링 비율
  messages:
    basename: messages, errors

  datasource:
    url: jdbc:mariadb://localhost:3307/jeeokshop_store_db?allowPublicKeyRetrieval=true&useSSL=false
    username: jeeok_user
    password: jeeok_pass
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        ues_sql_comment: true
        default_batch_fetch_size: 1000
    open-in-view: true

#actuator config
management:
  endpoints:
    web:
      exposure:
        include: refresh

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    root: info
    org.hibernate.SQL: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true
