server:
  port: 11000

actuator config
management:
  endpoints:
    web:
      exposure:
        include: refresh

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-server
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:10000
  cloud:
    gateway:
      routes:
        - id: member-server
          uri: lb://MEMBER-SERVER
          predicates:
            - Path=/member-server/**
            - Method=GET
          filters:
            - RewritePath=/member-server/(?<segment>.*),/$\{segment}

logging:
  level:
    root: debug
