server:
  port: 11000

#actuator config
management:
  endpoints:
    web:
      exposure:
        include: refresh

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-server
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:10000
  cloud:
    config:
      name: bootstrap
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigin: "http://localhost:5713"
            allowedMethod:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
              - PATCH
            allowedHeaders: '*'
            allow-credentials: true
      routes:
        - id: member-server
          uri: lb://MEMBER-SERVER
          predicates:
            - Path=/member-server/auth/login
            - Method=POST
          filters:
            - RewritePath=/member-server/(?<segment>.*),/$\{segment}
        - id: member-server
          uri: lb://MEMBER-SERVER
          predicates:
            - Path=/member-server/**
          filters:
            - RewritePath=/member-server/(?<segment>.*),/$\{segment}

        - id: jeeoklog-server
          uri: lb://JEEOKLOG-SERVER
          predicates:
            - Path=/jeeoklog-server/**
          filters:
            - RewritePath=/jeeoklog-server/(?<segment>.*),/$\{segment}

token:
  access-expired-time: 3600000
  refresh-expired-time: 604800000
  secret: $2a$10$q42lY7Y18xqrFt1qbODZIO4OMTeOxnrCe7tF3n9bazJinVE7VH5Pi
  refresh-token-name: refresh-token
  access-token-name: access-token