server:
  port: 11000

spring:
  application:
    name: apigateway-server
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:10000/
  messages:
    basename: messages, errors

  cloud:
    config:
      name: bootstrap
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigin: "http://localhost:5713"
            allowedMethod:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
              - PATCH
            allowedHeaders: '*'
            allow-credentials: true
      routes:
        #로그인
        - id: member-server
          uri: lb://MEMBER-SERVER/login
          predicates:
            - Path=/member-server/login
            - Method=POST
          filters:
            - RewritePath=/member-server/(?<segment>.*),/$\{segment}

        #회원가입, 재발행, 로그아웃, 토큰 조회
        - id: member-server
          uri: lb://MEMBER-SERVER/auth
          predicates:
            - Path=/member-server/auth/**
          filters:
            - RewritePath=/member-server/(?<segment>.*),/$\{segment}

        #회원 관리자
        - id: member-server
          uri: lb://MEMBER-SERVER/admin
          predicates:
            - Path=/member-server/admin/**
          filters:
            - AdminAuthorizationHeaderFilter
            - RewritePath=/member-server/(?<segment>.*),/$\{segment}

        #회원 사용자
        - id: member-server
          uri: lb://MEMBER-SERVER
          predicates:
            - Path=/member-server/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/member-server/(?<segment>.*),/$\{segment}

        #지옥로그 관리자
        - id: jeeoklog-server
          uri: lb://JEEOKLOG-SERVER/admin
          predicates:
            - Path=/jeeoklog-server/admin/**
          filters:
            - AdminAuthorizationHeaderFilter
            - RewritePath=/jeeoklog-server/(?<segment>.*),/$\{segment}

        #지옥로그 사용자
        - id: jeeoklog-server
          uri: lb://JEEOKLOG-SERVER
          predicates:
            - Path=/jeeoklog-server/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/jeeoklog-server/(?<segment>.*),/$\{segment}

        #지록숍 스토어 관리자
        - id: jeeokshop-store-server
          uri: lb://JEEOKSHOP-STORE-SERVER/admin
          predicates:
            - Path=/jeeokshop-store-server/admin/**
          filters:
            - AdminAuthorizationHeaderFilter
            - RewritePath=/jeeokshop-store-server/(?<segment>.*),/$\{segment}

        #지옥숍 스토어 매니저
        - id: jeeokshop-store-server
          uri: lb://JEEOKSHOP-STORE-SERVER/manager
          predicates:
            - Path=/jeeokshop-store-server/manager/**
          filters:
            - ManagerAuthorizationHeaderFilter
            - RewritePath=/jeeokshop-store-server/(?<segment>.*),/$\{segment}

        #지옥숍 스토어 사용자
        - id: jeeokshop-store-server
          uri: lb://JEEOKSHOP-STORE-SERVER
          predicates:
            - Path=/jeeokshop-store-server/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/jeeokshop-store-server/(?<segment>.*),/$\{segment}

        #지록숍 주문 관리자
        - id: jeeokshop-order-server
          uri: lb://JEEOKSHOP-ORDER-SERVER/admin
          predicates:
            - Path=/jeeokshop-order-server/admin/**
          filters:
            - AdminAuthorizationHeaderFilter
            - RewritePath=/jeeokshop-order-server/(?<segment>.*),/$\{segment}

        #지옥숍 주문 매니저
        - id: jeeokshop-order-server
          uri: lb://JEEOKSHOP-ORDER-SERVER/manager
          predicates:
            - Path=/jeeokshop-order-server/manager/**
          filters:
            - ManagerAuthorizationHeaderFilter
            - RewritePath=/jeeokshop-order-server/(?<segment>.*),/$\{segment}

        #지옥숍 주문 사용자
        - id: jeeokshop-order-server
          uri: lb://JEEOKSHOP-ORDER-SERVER
          predicates:
            - Path=/jeeokshop-order-server/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/jeeokshop-order-server/(?<segment>.*),/$\{segment}

        #지록숍 배달 관리자
        - id: jeeokshop-delivery-server
          uri: lb://JEEOKSHOP-DELIVERY-SERVER/admin
          predicates:
            - Path=/jeeokshop-delivery-server/admin/**
          filters:
            - AdminAuthorizationHeaderFilter
            - RewritePath=/jeeokshop-delivery-server/(?<segment>.*),/$\{segment}

        #지옥숍 배달 배달원
        - id: jeeokshop-delivery-server
          uri: lb://JEEOKSHOP-DELIVERY-SERVER/delivery
          predicates:
            - Path=/jeeokshop-delivery-server/delivery/**
          filters:
            - DeliverymanAuthorizationHeaderFilter
            - RewritePath=/jeeokshop-delivery-server/(?<segment>.*),/$\{segment}

#actuator config
management:
  endpoints:
    web:
      exposure:
        include: gateway
  endpoint:
    gateway:
      enabled: false #/actuator/gateway/routes 경로로 routes 보기

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

token:
  access-expired-time: 3600000
  refresh-expired-time: 604800000
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  refresh-token-name: refresh-token
  access-token-name: access-token