server:
  port: 11000

spring:
  application:
    name: apigateway-server
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:10000
  cloud:
    gateway:
      routes:
        - id: member-server
          uri: http://localhost:11001
          predicates:
            - Path=/member-server/**

#actuator config
management:
  endpoints:
    web:
      exposure:
        include: refresh

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka
    register-with-eureka: false #\uB098 \uC790\uC2E0\uC740 \uB4F1\uB85D\uD558\uC9C0 \uC54A\uC74C
    fetch-registry: false #\uB9C8\uC774\uD06C\uB85C\uC11C\uBE44\uC2A4 \uC778\uC2A4\uD134\uC2A4 \uBAA9\uB85D\uC744 \uB85C\uCEEC\uC5D0 \uCE90\uC2DC\uD560 \uAC83\uC778\uC9C0\uC758 \uC5EC\uBD80