server:
  port: 11001

spring:
  application:
    name: member-server
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:10000/

  datasource:
    url: jdbc:mariadb://localhost:3307/jeeok_member_db?allowPublicKeyRetrieval=true&useSSL=false
    username: jeeok_user
    password: jeeok_pass
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        ues_sql_comment: true
        default_batch_fetch_size: 1000
    open-in-view: true

  messages:
    basename: messages, errors

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    root: info
    org.hibernate.SQL: debug

token:
  access-expired-time: 3600000
  refresh-expired-time: 604800000
  secret: $2a$10$q42lY7Y18xqrFt1qbODZIO4OMTeOxnrCe7tF3n9bazJinVE7VH5Pi
  refresh-token-name: refresh-token
  access-token-name: access-token