version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: heech-zookeeper
    ports:
      - "2181:2181"
        #restart: unless-stopped

  kafka:
    #build: .
    image: wurstmeister/kafka
    container_name: heech-kafka
    ports:
      - "9092:9092"
    environment:
      DOCKER_API_VERSION: 1.22
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "order:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
        #restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: heech-zipkin
    ports:
      - "9411:9411"